### ISSUE TITLE
Reboot error on windows

### ISSUE THREAD

**Issue by 00x13** [InvisibleManVPN/InvisibleMan-XRayClient#100]
When Windows restarts, the Internet does not work, in order for the Internet to work, you need to connect and disconnect from the vpn. Please fix it!

**Comment by Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaao** [comment]
I also faced the same problem. Please correct.

**Comment by InvisibleManVPN** [comment]
Hello @00x13, @Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaao!
I need to investigate that and hope I will fix it soon. Thanks for submitting issue.

**Comment by 00x13** [comment]
> Hello @00x13, @Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaao! I need to investigate that and hope I will fix it soon. Thanks for submitting issue.

How can i help you? Some debug?

**Comment by InvisibleManVPN** [comment]
@00x13 In fact, when you turn off the system without closing the app, it cannot disable its system proxy settings and that's the reason for this problem. We need to looking for some possible solutions and choose the best one.

**Comment by 00x13** [comment]
> @00x13 In fact, when you turn off the system without closing the app, it cannot disable its system proxy settings and that's the reason for this problem. We need to looking for some possible solutions and choose the best one.


When you hit the shutdown button on the computer, if I understand correctly windows closes all applications.One solution: just clear the proxy during any application closure. Or give an alert window that says, clear proxy "Yes" , "no".

**Comment by 00x13** [comment]
Also, if the app is in autoload, you can clear the proxy every time you start the app, just in case.

**Comment by InvisibleManVPN** [comment]
Hey @00x13, @Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaao!
Refer to #162, this problem will be fixed in the next release.
