### ISSUE TITLE
Viruses?

### ISSUE THREAD

**Issue by Katrine2233** [InvisibleManVPN/InvisibleMan-XRayClient#113]
What do you mean?! Where do the viruses come from? O_o

https://www.virustotal.com/gui/file/96ac1c0ada75b01a9aaba0573d8e9ea05ab4caa09e5ebe2a873ac00f60139f1e
https://www.virustotal.com/gui/file/a2560ba6d0b3d4c575ec2742406f978f5fbaae1bd2287cb0b65af5f8bf1a446a
![Snag_24bf43c](https://github.com/user-attachments/assets/f5f5cc99-2110-4ee2-a731-1a2fd78fa576)
![Snag_24c7bdb](https://github.com/user-attachments/assets/c521e904-dbb1-4772-8ddd-ff796b2ac233)

**Comment by InvisibleManVPN** [comment]
Hey @Katrine2233!
I believe that's a false positive. I tried with the URL instead and it seems fine:

https://www.virustotal.com/gui/url/60e11d0fe9e03237c9a47da42375d5e2b5656f9bfa03bc03ce0d7a8e6fbb2455
https://www.virustotal.com/gui/url/42315d21f88c174c27ca8044101815b205ef412e3ae1629191367bc972bb80e9

**Comment by Katrine2233** [comment]
> Hey @Katrine2233! I believe that's a false positive. I tried with the URL instead and it seems fine:
> 
> https://www.virustotal.com/gui/url/60e11d0fe9e03237c9a47da42375d5e2b5656f9bfa03bc03ce0d7a8e6fbb2455 https://www.virustotal.com/gui/url/42315d21f88c174c27ca8044101815b205ef412e3ae1629191367bc972bb80e9

Some kind of magic. But I get it, thanks for your work. <3
