### ISSUE TITLE
Does app will support v2ray-json format?

### ISSUE THREAD

**Issue by Jolymmiles** [InvisibleManVPN/InvisibleMan-XRayClient#120]
Does app will support v2ray-json format?

**Comment by InvisibleManVPN** [comment]
Hey @Jolymmiles!
Currently, you can import v2ray `json`, `toml` and `yaml` config files to the app.

![image](https://github.com/user-attachments/assets/979baa93-16ae-458e-aa0d-62dd46d260fd)
