### ISSUE TITLE
Directory error kills browsers

### ISSUE THREAD

**Issue by Verrity** [InvisibleManVPN/InvisibleMan-XRayClient#134]
If the Settings->Log->"Logs path" contains Cyrillic, then the client's UI is buggy, the button does not work, and most importantly, browsers can no longer load pages, and the connection to microsoft services does not work, although white ip addresses can ping. Deleting and killing processes does not help fix the problem. 
To fix it, you need to specify the "Logs path" path that does not contain Cyrillic. In this case, the root of the program can be located along a path containing Cyrillic without problems.
![image](https://github.com/user-attachments/assets/94de62d5-9c1c-42c1-b675-b7549ce85b6b)

**Comment by Bushroott** [comment]
Yes, it's obvious. No letters of the national alphabets in the names of directories for executable files, swaps/temps, logs, DLL`s etc.

**Comment by InvisibleManVPN** [comment]
Hey @Verrity , @Bushroott 
Thank you for submitting this issue. That was a significant problem and many users have this. Now, I fixed it and from the next release, you don't need to choose a full-English path!

Many thanks, again!
