### ISSUE TITLE
Problems with JSON import

### ISSUE THREAD

**Issue by HominoDev** [InvisibleManVPN/InvisibleMan-XRayClient#142]
The JSON format is definitely correct since I already imported it on my PC. The problem occurs with a friend on a 32-bit machine, "Windows 10 32bit"

![image](https://github.com/user-attachments/assets/ed65d1b0-11eb-4b33-9136-d697594c8e71)

**Comment by InvisibleManVPN** [comment]
Hey @HominoDev
Maybe you've put the app (or config) in a non-English directory. Make sure the directory is full-English and then test it again. This is a bad problem but currently, I fixed it and it will be OK from the upcoming release in a few days.
