### ISSUE TITLE
This app is more friendly to older computers, kudos!

### ISSUE THREAD

**Issue by DbuyCN** [InvisibleManVPN/InvisibleMan-XRayClient#148]
This app is more friendly to older computers, kudos! hope to add Chinese language.
Windows7

**Comment by InvisibleManVPN** [comment]
Hello @DbuyCN 
Thanks for your message! You can read [this](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/blob/master/Language.md) instruction to know how to add languages. Any contribution is welcomed!
Also, you can support the app by sharing it with others.
