### ISSUE TITLE
An incorrectly disabled program breaks the default connection

### ISSUE THREAD

**Issue by dzeremov** [InvisibleManVPN/InvisibleMan-XRayClient#159]
If I turn off my PC while program is running with VPN it will restart with disabled VPN but also with "broken" internet connection so default connection doesn't work until I re - run VPN and disable VPN

**Comment by kesha4** [comment]
+1

**Comment by InvisibleManVPN** [comment]
Hey @dzeremov, @kesha4!
Thanks for submitting the issue. Refer to #162, this problem will be fixed in the next release.
