### ISSUE TITLE
Opening the app and importing subscription from the browser's address bar

### ISSUE THREAD

**Issue by kesha4** [InvisibleManVPN/InvisibleMan-XRayClient#160]
Please implement the function of importing a subscription from a link in the browser. Most competing applications have such a function, it allows you to add a subscription in 2 clicks.

_For example, the appearance of similar links in Hiddify and v2rayTun:_
- hiddify://import/https://domain.ru/subscription_link/
- v2raytun://import-sub?url=https://domain.ru/subscription_link/

**Comment by InvisibleManVPN** [comment]
Hey @kesha4
We already have this feature in the app:
- **Config:** `invxray://config/{the link of the config (vless, vmess, trojan, shadowsocks)}`
- **Subscription:** `invxray://subscription/{the link of the subscription}`

For more information, see [InvisibleMan-XRay v2.3.2 - Changelog](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/releases/tag/v2.3.2)
