### ISSUE TITLE
Windows defender报毒

### ISSUE THREAD

**Issue by RadixIsatidis** [InvisibleManVPN/InvisibleMan-XRayClient#39]
系统给提示，Trojan:Win32/Wacatac.H!ml

**Comment by InvisibleManVPN** [comment]
Hi @RadixIsatidis!
Thanks for submitting this issue. We believe that this is a false positive as they occurs on .Net apps previously (See https://github.com/dotnet/runtime/issues/35167). We submitted the app to https://www.microsoft.com/en-us/wdsi/filesubmission to check for malware and after that, we'll give you the result.

**Comment by InvisibleManVPN** [comment]
This is the answer from Microsoft analyst:

> We cannot reproduce any detection on the file. If the detection is still observed, follow the steps below to capture support log files from the system reporting detection.
> 
> From an elevated command prompt, change to directory "%programfiles%\windows defender" and execute mpcmdrun.exe with option GetFiles:
> cd "%programfiles%\windows defender"
> mpcmdrun.exe -GetFiles
> 
> All created log files will be compressed into MPSupportFiles.cab. Please send us the detected file and MPSupportFiles.cab using https://aka.ms/wdsi. We will continue the investigation once we receive the support log files.
> 
> Thank you for contacting Microsoft.

Currently, we close this issue. If the problem occurs again, reopen it.
