### ISSUE TITLE
3rd Part Apps Not work

### ISSUE THREAD

**Issue by rezahaddady** [InvisibleManVPN/InvisibleMan-XRayClient#43]
Hi
After I test this app, 3rd party apps like Telegram, Whatsapp and ... not use this application to connect 
So in my country Telegram and Whatsapp are filter and I can not Use them but browsers work perfect
same problem in V2rayN
Only Nekoray after select vpn mode all apps work
Please solve this issue

**Comment by InvisibleManVPN** [comment]
Hi @rezahaddady!

Thanks for your comment. That's a good suggestion. we'll investigate it and give you feedback. However, you can set your system proxy with some 3rd apps. 

For example, in Telegram follow these steps:
- Connect to the proxy via Invisible Man XRay
- Open the Telegram app
- Go to `Settings > Advanced > Connection type`
- In the opened window click on `Use system proxy settings`
- Now you can use Telegram with your system proxy settings!

![image](https://user-images.githubusercontent.com/46280804/228085402-8f80bbe3-5894-4e25-8098-2559a240959d.png)

**Comment by rezahaddady** [comment]
HiThank you for responseI know Telegram Proxy setting and I use it with Nekoray but V2rayN and InvisibleNan not work with this method.I tested it before email youyour app need Vpn Mode like NekoraySent from my iPhoneOn Mar 28, 2023, at 02:29, Invisible Man ***@***.***> wrote:﻿
Hi @rezahaddady!
Thanks for your comment. That's a good suggestion. we'll investigate it and give you feedback. However, you can set your system proxy with some 3rd apps.
For example, in Telegram follow these steps:

Connect to the proxy via Invisible Man XRay
Open the Telegram app
Go to Settings > Advanced > Connection type
In the opened window click on Use system proxy settings
Now you can use Telegram with your system proxy settings!

**Comment by firefoxOnFire** [comment]
is there any plan on adding vpn ?

**Comment by rezahaddady** [comment]
Your app is incredible for web surffingbut installed app like whatsapp can not use itEven Telegram that have proxy setting not work. Same problem in V2rayN,Clash,...only NEKORAY with help of [[ vpn mode]] in its setting working. you must check nekoray way and bring this option to InvisibleManSent from my iPhoneOn Mar 30, 2023, at 17:57, firefoxOnFire ***@***.***> wrote:﻿
is there any plan on adding vpn ?

**Comment by InvisibleManVPN** [comment]
Hi @firefoxOnFire and @rezahaddady!<br/>Currently, we're working on some other features. Although we added this issue to our tasks list, we need more time for R&D. we'll give you our decision in a couple of days.

Thank you for your patience

**Comment by rezahaddady** [comment]
Good to hear thatVery nice jobSent from my iPhoneOn Mar 31, 2023, at 00:15, Invisible Man ***@***.***> wrote:﻿
Hi @firefoxOnFire and @rezahaddady!Currently, we're working on some other features. Although we added this issue to our tasks list, we need more time for R&D. we'll give you our decision in a couple of days.
Thank you for your patience

**Comment by firefoxOnFire** [comment]
> Hi @firefoxOnFire and @rezahaddady!Currently, we're working on some other features. Although we added this issue to our tasks list, we need more time for R&D. we'll give you our decision in a couple of days.
> 
> Thank you for your patience

You are great thanks 😊

**Comment by InvisibleManVPN** [comment]
@firefoxOnFire @rezahaddady
Now, we added our new TUN mode feature that helps you to tunnel all your system's traffic. Currently, we close this issue.
Wait for the new version of Invisible Man XRay! we'll try to publish it as soon as possible. Then you can use this feature.

Thanks for suggesting this feature!

**Comment by rezahaddady** [comment]
Thank You So Much
you are definition of what support team should be
