### ISSUE TITLE
where is the log files?

### ISSUE THREAD

**Issue by guoapeng** [InvisibleManVPN/InvisibleMan-XRayClient#46]
I would like to check in case of any issue on client. but I can't get any useful information. could you advice where I can get the logs like connection status, routing rule etc.

**Comment by InvisibleManVPN** [comment]
Hi @guoapeng!
Currently, we don't have any section in the app to shows you logs. But on the main window, you can click on **Manage server configuration** and click edit on each config file that you want. 

![image](https://user-images.githubusercontent.com/46280804/232232289-718fc395-b608-4bec-b15f-0e612df29286.png)

In the `log` section, you can set the `loglevel` and path for `access` and `error` files. For example:

```
{
   "log":{
      "access":"C:\\access.txt",
      "error":"C:\\error.txt",
      "loglevel":"debug"
   },
   "inbounds":[{
      ...
   }]
   ...
}
```

For more information, see https://guide.v2fly.org/en_US/basics/log.html
