### ISSUE TITLE
very hard adding server

### ISSUE THREAD

**Issue by testermania** [InvisibleManVPN/InvisibleMan-XRayClient#47]
vless://uuid@url:443?encryption=none&security=tls&type=ws&host=www.url.com&path=%2fpath%3fuser%3duser#pass

no paste clipboard

**Comment by testermania** [comment]
It shows connected but no loading any website.

**Comment by InvisibleManVPN** [comment]
> vless://uuid@url:443?encryption=none&security=tls&type=ws&host=www.url.com&path=%2fpath%3fuser%3duser#pass
> 
> no paste clipboard

Hi @testermania! You just need to copy the link and go to **Manage server configuration**. Then click on **+** button, Choose **Import from link** and paste your link.

**Comment by InvisibleManVPN** [comment]
> It shows connected but no loading any website.
> 
> `{"log":{"access":"","error":"","loglevel":"warning"},"inbounds":[{"tag":null,"port":10801,"listen":"127.0.0.1","protocol":"http","sniffing":null,"settings":{"auth":null,"udp":true,"ip":null,"address":null,"clients":null,"decryption":null,"allowTransparent":false,"accounts":null},"streamSettings":null}],"outbounds":[{"tag":null,"protocol":"vless","settings":{"vnext":[{"address":"myserver.com","port":443,"users":[{"id":"4f17e173-4af9-5041-9662-f6c27e0decfd","alterId":0,"email":"t@t.tt","security":null,"encryption":"none","flow":""}]}],"servers":null,"response":null,"domainStrategy":null,"userLevel":0},"streamSettings":{"network":"ws","security":"tls","tlsSettings":{"allowInsecure":true,"serverName":"www.bing.com","alpn":[""],"fingerprint":""},"tcpSettings":null,"kcpSettings":null,"wsSettings":{"path":"/mypath","headers":{"Host":"www.bing.com","User-Agent":null}},"httpSettings":null,"quicSettings":null,"xtlsSettings":null,"grpcSettings":null,"realitySettings":null},"mux":null}],"stats":null,"api":null,"policy":null,"dns":null,"routing":null}`

You're right. In fact **Connected** status shows that the app can connect to the xray-core successfully and it's different from connecting to the server. We need to change **Connected** to something else like **Running**. But if you want to see that your configuration server is available or not, you can click on **Manage server configuration**, click on **Check** button, and wait for the server's response.

![image](https://user-images.githubusercontent.com/46280804/232234493-21dee063-54ed-44a2-aa2e-5b0d22f6eb1b.png)
