### ISSUE TITLE
Reality not wokring

### ISSUE THREAD

**Issue by mortada-jafar** [InvisibleManVPN/InvisibleMan-XRayClient#48]
Reality feature not working. I tested the reality feature and found that the public key was not imported. I entered it manually, but it still didn't work. Could you please check it? Thank you

**Comment by InvisibleManVPN** [comment]
Hi @mortada-jafar! Thanks for submitting this issue. Do you have the latest version of the app?

**Comment by mortada-jafar** [comment]
yes,I tested this version InvisibleMan-XRay v0.4.2

**Comment by mortada-jafar** [comment]
the app connected but no internet on another apps work fine

**Comment by mortada-jafar** [comment]
please check this connation
`vless://mortada3@128.140.40.61:80?type=tcp&security=reality&sni=codepen.io&pbk=rJFC3dUjJxMnVZiUGzmf_LFsJUwFWY-CU5RQgFOHCWM&flow=&fp=firefox#reality-6`

**Comment by mortada-jafar** [comment]
i think the problem is from UUID !? Does the app work with a valid UUID?

**Comment by InvisibleManVPN** [comment]
@mortada-jafar We checked this issue. You're right. It's a bug. We'll fix that and give you feedback.
Thanks for submitting this bug!

**Comment by uprt** [comment]
As I see, the current version InvisibleMan is based on XRay 1.7.5, XRay 1.7.5 doesn't support XTLS-Reality, so it will not work anyway (and the words "Reality support" in InvisibleMan changelog are misleading). Need to wait for the upgrade of the core to 1.8.1

So here is the feature request for @InvisibleManVPN : could you please display somewhere (e.g. in the "About" box) a version of bundled XRay-core? This will be helpful. And also would be very nice to get access to the XRay logs (maybe not in the UI, can be a log file), this also may be very useful for troubleshooting.

**Comment by uprt** [comment]
I created issues #55 and #56, can't find how to put the label, seems like only the repo owner can do it.

**Comment by InvisibleManVPN** [comment]
@uprt That's great. I put them, label.

**Comment by InvisibleManVPN** [comment]
@mortada-jafar, @uprt By merging #67 and #68, Invisible Man XRay will support reality from the next release. Now, I close this issue.
Thanks for submitting this issue!
