### ISSUE TITLE
[feature] XRay version display in the UI

### ISSUE THREAD

**Issue by uprt** [InvisibleManVPN/InvisibleMan-XRayClient#55]
Could you please display somewhere (e.g. in the "About" box) a version of bundled XRay-core? This will be helpful to understand what exactly features are supported.

**Comment by InvisibleManVPN** [comment]
@uprt By adding #60, you can see application and xray core version in the about window.
To see this feature, wait for the new version of Invisible Man XRay.

Thanks for your feature suggestion!

![image](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/46280804/a5ad7bbe-0dd6-4e26-ab29-23e23339b83b)
