### ISSUE TITLE
[feature] XRay logs access

### ISSUE THREAD

**Issue by uprt** [InvisibleManVPN/InvisibleMan-XRayClient#56]
Would be very nice to get access to the XRay logs (maybe not in the UI, can be a log file), this also may be very useful for troubleshooting to understand why the connection doesn't work.
Also would be nice to have the possibility to adjust the log level for it.

**Comment by InvisibleManVPN** [comment]
@uprt By adding the settings menu, you can set the log level and see the log files. Now, I close this issue.
To use this feature, wait for the new version of Invisible Man XRay.

Thanks for your feature suggestion!

![image](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/46280804/31ea182e-f0b3-4707-84fb-ce8df357e434)
