### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by jiushibushuo** [InvisibleManVPN/InvisibleMan-XRayClient#57]
Haiyaa...There is no even simple manual on the website!

proxy mode,
IP:127.0.0.1
what protocol?
what port?

**Comment by InvisibleManVPN** [comment]
Hi @jiushibushuo!
This project is under development and this will be added to the **Settings** menu in the new release.
Currently, the **protocol** is **http** in **proxy** mode and **socks** in **TUN** mode, and the port is **10801**.

**Comment by jiushibushuo** [comment]
> Hi @jiushibushuo! This project is under development and this will be added to the **Settings** menu in the new release. Currently, the **protocol** is **http** in **proxy** mode and **socks** in **TUN** mode, and the port is **10801**.

Thanks!
