### ISSUE TITLE
link of vpn servers

### ISSUE THREAD

**Issue by ivanjimenez** [InvisibleManVPN/InvisibleMan-XRayClient#58]
Hi, is it possible provide a simple test json server file configuration to test the app or maybe a link?
Thanks a bunch.
BR

**Comment by InvisibleManVPN** [comment]
Hi @ivanjimenez!
For testing, you can add any v2ray config file to the app and click on the **Check** button to test it.

![image](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/46280804/635e124b-5ec2-4123-a0d8-c8ce41cc4bbd)

Maybe I couldn't get what you mean. So, if needed please give me more information.
Thanks

**Comment by ivanjimenez** [comment]
Hi, I have not the config.json. When app starts and "Run" it prints "no configuration file". And then I try to add server config file and gives me two options: import file o set an url.

![image](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/908544/e7c9019e-4933-4f48-a286-004c7af8d7ea)

I don't know what kind of config file is used for this.

Hope I have done a better explanation of my doubts.

Thanks a bunch.
BR

**Comment by tkmw1985** [comment]
It uses json format or provided vpn link wmess, vless i.t.c

**Comment by InvisibleManVPN** [comment]
@ivanjimenez Any type of v2ray config file and `vmess`, `vless`, `trojan` and `shadowsocks` links was supported.
For more information, read [Project V - Configuration Overview](https://www.v2ray.com/en/configuration/overview.html)
