### ISSUE TITLE
Core Update

### ISSUE THREAD

**Issue by alidxdydz** [InvisibleManVPN/InvisibleMan-XRayClient#63]
Hi,

Could you please update xray core to v1.8.3?

**Comment by InvisibleManVPN** [comment]
Hi @alidxdydz!
We're waiting for the **Latest** xray-core release. Currently, v1.8.* is **pre-release**. But we will investigate this issue to add a feature that allows users to switch between **Latest** or **pre-release** xray-core version and then we'll give you feedback.

Thanks for submitting this issue!

**Comment by alidxdydz** [comment]
I believe that they aren't going to release a new version untill next year.
https://t.me/projectXtls/103

New pre-release versions have added so many features which are very usefull.

I wonder if you just release .dll file, could we manually replace it with previous one?

**Comment by InvisibleManVPN** [comment]
@alidxdydz That's correct. And this is the reason that we want to investigate this issue.
Yes, you can. Maybe, we added two dll files in our release for both **Latest** and **pre-release** versions.

I just make the `XRayCore.dll` v1.8.3 file for you. You can download it extract and replace it in the `Libraries` path.

[Download XRayCore v1.8.3](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/files/11887606/XRayCore.zip)

But if you know how to export dll file, you can build your own `XRayCore.dll` file each time you want and replace it.

- Clone the project.
- Go to the `xray-wrapper` folder.
- Open `go.mod` file.
- In line 5, change `require github.com/xtls/xray-core v1.7.5` to `require github.com/xtls/xray-core v1.8.3`.
- Run `go mod tidy` and wait for download files.

Now, you can export v1.8.3 of `XRayCore.dll` file by doing these instructions:

```
go build --buildmode=c-shared -o XRayCore.dll -trimpath -ldflags "-s -w -buildid=" .
```

And copy this into the `Libraries` folder of the application.

**Comment by alidxdydz** [comment]
I sicerely appreciate your help.
Adding multiple cores would be wonderful.
Thank you very much.

Just one more question.
Can someone create .dll files for Hysteria and Sing-Box core?

**Comment by InvisibleManVPN** [comment]
@alidxdydz In short, yes, you can. If you make a wrapper for them that implements all the functions in `wrapper.go` and `config.go` which have the `//export` comments at the top of them, you can use these cores in the app.
But you need to check their functionality.

**Comment by alidxdydz** [comment]
Thank you for clarification and .dll file for v.1.8.3

**Comment by InvisibleManVPN** [comment]
@alidxdydz We upgraded xray core version to v1.8.3 for our next release. Now, I close this issue.
Thanks for your suggestion!
