### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by ThatQne** [InvisibleManVPN/InvisibleMan-XRayClient#65]
How do I use configs

**Comment by InvisibleManVPN** [comment]
Hi @ThatQne!
You can use all types of v2ray configs by importing them as **File** or **Link**.

After opening the app, click on **Manage server configuration**. In the opened window, click on the **Plus** button.
Now, you see two options for importing your config.

- If you have a v2ray json file, you should choose **Import config file** and then import your file.
- But if you have v2ray link (Like `vmess://`, `vless://`, `ss://` or `trojan://`), you should choose **Import from link** and paste your link.
