### ISSUE TITLE
Import multiple vpn configs by subscription file!

### ISSUE THREAD

**Issue by jba-tm** [InvisibleManVPN/InvisibleMan-XRayClient#76]
Feature request!!!
Import vmess, vless configs by subscription link or file

**Comment by InvisibleManVPN** [comment]
Hi @jba-tm!
Thanks for submitting this issue. We'll investigate it and send you feedback.

**Comment by InvisibleManVPN** [comment]
@jba-tm We added this feature to the app. In the next release, Invisible Man XRay supports subscription links.
Now, I close this issue.

Thanks for your suggestion!
