### ISSUE TITLE
URL Scheme support

### ISSUE THREAD

**Issue by iambabyninja** [InvisibleManVPN/InvisibleMan-XRayClient#78]
Hello!
If we're talking about adding a subscription link, which is very important for a modern client, I kindly request you to consider the possibility of adding so-called URL schemes to your application. They will enhance the user experience and make interaction easier.
For example, many applications on all platforms support this feature:
CLASH:
clashx://install-config?url=URL
ShadowRocket:
sub://URL
You can find all the examples here:
https://docs.marzban.ru/examples/url-scheme

We need this in order to allow users to add a subscription to the application with just one click from the subscription page.
![image](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/104270279/26e8b78e-7ab8-4959-bc4f-c741f8dae086)
If you add this feature, along with support for sub pages, your application will become the ultimate solution for Windows users.

Thanx!

**Comment by InvisibleManVPN** [comment]
Hi @Iambabyninja and thank you for your suggestion!
That's a cool idea. We'll work on it and give you the feedback.

**Comment by InvisibleManVPN** [comment]
@iambabyninja Thanks for your suggestion. This feature will be available in the next release. I close this issue.

**Comment by iambabyninja** [comment]
@InvisibleManVPN big thanx 4 your work 🤝❤️

**Comment by kesha4** [comment]
Hello! I used this functionality and noticed that the application does not take into account the Headers transmitted when importing a Subscription via the link:
profile-title - plain-text or base64 for unicode - defines the name of the subscription in the application
profile-update-interval - int - interval in days after which the configurations will be automatically requested again

Also, the subscription name in the application allows you to enter only Latin symbols, and not any unicode/utf-8

Please improve the functionality, I really want to recommend your application in my service, but these shortcomings are in the way.

**Comment by kesha4** [comment]
![image](https://github.com/user-attachments/assets/39ef7544-0cae-40a5-9afa-f889cf91bda4)
