### ISSUE TITLE
Enable/disable system proxy option

### ISSUE THREAD

**Issue by sithius82** [InvisibleManVPN/InvisibleMan-XRayClient#80]
Hello DevTeam!

This client sets system proxy (in Control Panel -> Internet Options for example) for the user. Is it possible to add functionality - for not to set this setting automatically? 

I'm asking because of the following reason - we're using this wonderful Client for local VPN proxy, so it's not needed anywhere else for user. Every time the connection is up - it sets up proxy settings in control panel.

Can you add switch for setting/not setting system proxy option?

**Comment by InvisibleManVPN** [comment]
Hi @sithius82!
Thanks for your suggestion. We'll check it and send you the feedback.

**Comment by Winand** [comment]
Yes, I don't need a system-wide proxy at all, because I use Proxy SwitchyOmega browser extension, which can connect to a specified port.

**Comment by InvisibleManVPN** [comment]
Hello, @sithius82 @Winand
This feature was added to the app. So, you can use it in the next release. Now, I'm going to close this issue.

Thanks
