### ISSUE TITLE
TON

### ISSUE THREAD

**Issue by lifeindarkside** [InvisibleManVPN/InvisibleMan-XRayClient#85]
Please, add TON to get donation.

**Comment by InvisibleManVPN** [comment]
@lifeindarkside Thanks for your support!
I updated **README** and added **TON** in the [**Donation**](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient#donation) section.

**Comment by lifeindarkside** [comment]
check pls
![image](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/66727826/bc6c83d0-022d-4d8b-882c-279cbf7645d9)

**Comment by InvisibleManVPN** [comment]
@lifeindarkside Thank you for your support! It's very valuable for me.
Hope you enjoy Invisible Man XRay.
