### ISSUE TITLE
TUN mode dont work

### ISSUE THREAD

**Issue by thezass** [InvisibleManVPN/InvisibleMan-XRayClient#87]
first of all thanks for building best client for windows

i have problem that when i enable tun mode it dont work and my laptop netowrk dont work until i disable tun mode on invisiable man

**Comment by lifeindarkside** [comment]
yes. i try it again. don't work tun mode

**Comment by InvisibleManVPN** [comment]
Hi, @thezass!
Can you do [these steps](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/issues/79#issuecomment-1729502689) and check whether you have the InvisibleMan-XRay network connection or not?

**Comment by thezass** [comment]
yes i have connection in my control panel but still tun mode dont work

**Comment by InvisibleManVPN** [comment]
@thezass OK, thanks for your report. I'll check it.

**Comment by RealKorush** [comment]
Hi 
![Screenshot 2023-10-07 065640](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/68956993/72420916-f76e-4e80-b9c6-931913446c1b)
How should I solve this problem?

**Comment by InvisibleManVPN** [comment]
Hi @RealKorush!
First, did you check whether you have the InvisibleMan-XRay network connection or not? https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/issues/87#issuecomment-1742051212
This error occurs when the application can't connect to the **InvisibleMan-TUN service** port.
Try to change the port from: **Settings > Port > TUN port** and test it again.

![image](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/46280804/28e5a4a0-6da7-4af6-99c8-be03edadfa1c)

**Comment by lifeindarkside** [comment]
For me, work ok
