### ISSUE TITLE
A strange question about socks

### ISSUE THREAD

**Issue by wanliyunyan** [InvisibleManVPN/InvisibleMan-XRayClient#91]
If I set the mode to proxy and the protocol to socks, the proxy does not seem to take effect. I cannot access some websites when I visit them. If the mode is proxy and the protocol is http, I can access any website at this time. At this time, I change the protocol to socks. Then I can also visit these websites that have been visited

**Comment by InvisibleManVPN** [comment]
Hi @wanliyunyan!
Thanks for submitting this issue. I need to investigate it and try to fix that as soon as possible.

**Comment by InvisibleManVPN** [comment]
Hey @wanliyunyan!
Can you please download the new version and check whether the problem still happened or not?

Thank you!

**Comment by wanliyunyan** [comment]
@InvisibleManVPN The program cannot start. However, when I click to check, there is a connection.

**Comment by wanliyunyan** [comment]
![image](https://github.com/user-attachments/assets/d5ed6ee4-f2cf-44db-a7e5-0eb7005afa64)
![image](https://github.com/user-attachments/assets/344a2652-18c8-4766-9d41-65e449baa841)
![image](https://github.com/user-attachments/assets/bb377ba7-47f7-4c92-acce-43996dd2128f)
