### ISSUE TITLE
Fix SOCKS system proxy (solution provided)

### ISSUE THREAD

**Issue by splithor1zon** [InvisibleManVPN/InvisibleMan-XRayClient#92]
It is neccessary to prepend "socks=" in the IP address fields of Windows system proxy when using socks. Without it system proxy is set as http proxy by default. See the picture of how the Windows 11 proxy settings should look like when using socks proxy. Thank you!
![obrázok](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/43297553/9b56b975-f87e-4e43-a600-a7c9d5322b08)

**Comment by InvisibleManVPN** [comment]
Hi @splithor1zon!
Thanks for the solution. I'll fix that in the next release. Also, any contribution is welcomed!

**Comment by InvisibleManVPN** [comment]
Hey @splithor1zon, thanks for your solution. I already added this feature and it will be accessible from the next release. Now, I close this issue.
