### ISSUE TITLE
Tunneling mode creates dozens of Ethernet adapters

### ISSUE THREAD

**Issue by memeTimofei** [InvisibleManVPN/InvisibleMan-XRayClient#93]
<img width="248" alt="image" src="https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/151925802/3e31400a-0a4f-47ae-b246-c36647ea9c29">

When starting IM XRay 1.4.4 on Win11 in the tunneling mode it creates a new enumerated connecton each time (that is IM-XRay "19" in the screenshot's case). Seems to have no effect on the very work of the client but still the fact catches my eye each time.

Thanks

**Comment by InvisibleManVPN** [comment]
Hi @memeTimofei!
Thanks for submitting the issue. I'll check it.

**Comment by InvisibleManVPN** [comment]
Hi @Maneeha1234SL, thanks for noticing the issue.
Yeah, you're right. This problem isn't fixed in v2.1.2. But I will fix it soon.

**Comment by InvisibleManVPN** [comment]
@memeTimofei @Maneeha1234SL Hello!
This issue resolved by did a fix on **Invisible Man TUN** service ([see this](https://github.com/InvisibleManVPN/InvisibleMan-TUN/pull/10))
I also updated a new release for this service ([InvisibleMan-TUN v0.3.4](https://github.com/InvisibleManVPN/InvisibleMan-TUN/releases/tag/v0.3.4))
So, you can wait for the next release of **Invisible Man XRay** or you can download version **0.3.4** of **Invisible Man TUN** and extract it manually into the `{the path you installed Invisible Man XRay}/TUN` directory.

Now, I close this issue, but if you have any other problem, feel free to create a new issue!
