### ISSUE TITLE
The problem with routing all traffic through a VPN in Windows 11

### ISSUE THREAD

**Issue by habr** [InvisibleManVPN/InvisibleMan-XRayClient#95]
I ran into a problem using the Invisible Man-X Ray Client in Windows 11. Despite an active VPN connection, it seems that not all computer traffic passes through the VPN. Here are the steps I have taken:

I installed and configured the Invisible Man-X Ray Client on Windows 11.
Connected to the VPN server.
I checked that the VPN is active, but noticed that some applications/services still use a direct connection rather than a VPN.
My questions:

Are there any specific settings in the Invisible Man-X Ray Client that need to be configured to force routing of all traffic through the VPN?
Can you suggest steps to fix this problem or point out possible settings in Windows 11 that may affect this?
Thank you in advance for your help and advice.

With respect, habr

**Comment by aK0nshin** [comment]
Same stuff on windows 10.
I've connected to thr VPN server in proxy mode. 
If I check my ip in Crome on site like (ipinfo.io/ip) - it shows new(changed) ip. 
If i go to cmd and run something like `curl ipinfo.io/ip` it returns me the old(unchanged) ip.
Command `netsh winhttp show proxy` returns that direct acess is configured without any proxies.
In Windows Network Settings->Proxy "Determine parameters automatically" option is checked.

**Comment by InvisibleManVPN** [comment]
Hi @habr and @aK0nshin!
To route all the traffic of your system through the VPN, you should use **TUN** mode. The **Proxy** mode just routes apps that support **System Proxy** settings.

![image](https://github.com/InvisibleManVPN/InvisibleMan-XRayClient/assets/46280804/feb7d172-284e-48b7-b87e-a4979180a118)
