### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by webdevelopland** [InvisibleManVPN/InvisibleMan-XRayClient#99]
Is there any way to use this client on ubuntu?  
AFAIU there's only `.exe` version on the releases

**Comment by InvisibleManVPN** [comment]
Hello @webdevelopland, Thanks for your message.
Currently, I'm working on rewriting Invisible Man XRay to port it to various platforms. But it needs time, so currently, Invisible Man XRay just works for Windows.

**Comment by webdevelopland** [comment]
@InvisibleManVPN Thank you for your work!
XRayClient is amazing, I use it everyday

**Comment by webdevelopland** [comment]
Closed as completed?
Is it implemented already? Or you just closed as a duplicated?

**Comment by InvisibleManVPN** [comment]
Sorry @webdevelopland, I should close another issue as a duplicate.
